"""users table

Revision ID: 36189a12994a
Revises: e3b2474a2593
Create Date: 2020-08-08 14:42:32.472044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36189a12994a'
down_revision = 'e3b2474a2593'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_column('user', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('user', 'id')
    # ### end Alembic commands ###
