"""users table

Revision ID: 445cfba0194a
Revises: 36189a12994a
Create Date: 2020-08-08 16:39:43.709427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '445cfba0194a'
down_revision = '36189a12994a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_username', table_name='user')
    op.create_unique_constraint(None, 'user', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.create_index('ix_user_username', 'user', ['username'], unique=True)
    # ### end Alembic commands ###
